# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 832427d8ea3fe8a5c1cad70f10159b3ebd4458610ff53d61e7e4cc4212ab15fde5212d9c259df619a04c618a676a15a4b98f970dcdfc5a9c346d7bf020dddc9e

test:
  secret_key_base: b4938d19e873105b84d5cadb2efd47b8d4e0f6965449452b857ed15080b1c9b22a5672d3cd5b8401cc16390f0a5830597d72d0ee10324c30b53fa5a1ec8bc6c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
